# Generated by Django 5.1.6 on 2025-03-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_profile_securityquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='securityquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='securityquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.securityquestion'),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_text',
            field=models.CharField(default='Place holder Question', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='music/images/default_profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
